changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Documentation 📚
      labels:
        - documentation
    - title: Breaking Changes 💥
      labels:
        - breaking-change
    - title: Exciting New Features ✨
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
